"""Description

Revision ID: 12e4ee70f711
Revises: 3c2b44064498
Create Date: 2025-08-24 01:23:50.320615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e4ee70f711'
down_revision = '3c2b44064498'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
