"""Add deployed APIs and integrations tables

Revision ID: 7fad20a7ca87
Revises: 
Create Date: 2025-08-25 17:02:19.173480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fad20a7ca87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('file_extension', sa.String(length=20), nullable=True),
    sa.Column('is_system_template', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('parent_template_id', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_templates_id'), 'api_templates', ['id'], unique=False)
    op.create_index(op.f('ix_api_templates_name'), 'api_templates', ['name'], unique=True)
    op.create_table('field_mapping_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('template_config', sa.JSON(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('is_system_template', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_mapping_templates_id'), 'field_mapping_templates', ['id'], unique=False)
    op.create_index(op.f('ix_field_mapping_templates_name'), 'field_mapping_templates', ['name'], unique=False)
    op.create_table('lenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_version', sa.String(length=50), nullable=True),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('auth_config', sa.JSON(), nullable=True),
    sa.Column('openapi_spec_url', sa.String(length=500), nullable=True),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('support_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lenders_id'), 'lenders', ['id'], unique=False)
    op.create_index(op.f('ix_lenders_name'), 'lenders', ['name'], unique=True)
    op.create_table('master_source_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('field_type', sa.Enum('STRING', 'NUMBER', 'BOOLEAN', 'OBJECT', 'ARRAY', 'DATE', 'EMAIL', 'PHONE', 'CURRENCY', name='datatype'), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('sample_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_source_fields_id'), 'master_source_fields', ['id'], unique=False)
    op.create_index(op.f('ix_master_source_fields_name'), 'master_source_fields', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('api_quota', sa.Integer(), nullable=True),
    sa.Column('api_usage', sa.Integer(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('endpoint_path', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('request_body_schema', sa.JSON(), nullable=True),
    sa.Column('response_schema', sa.JSON(), nullable=True),
    sa.Column('success_codes', sa.JSON(), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=True),
    sa.Column('auth_parameters', sa.JSON(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('retry_config', sa.JSON(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('data_mapping', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deprecated', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_configs_id'), 'api_configs', ['id'], unique=False)
    op.create_table('custom_target_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('field_type', sa.Enum('STRING', 'NUMBER', 'BOOLEAN', 'OBJECT', 'ARRAY', 'DATE', 'EMAIL', 'PHONE', 'CURRENCY', name='datatype'), nullable=True),
    sa.Column('field_path', sa.String(length=500), nullable=True),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_target_fields_id'), 'custom_target_fields', ['id'], unique=False)
    op.create_index(op.f('ix_custom_target_fields_name'), 'custom_target_fields', ['name'], unique=False)
    op.create_table('deployed_apis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('step_config', sa.JSON(), nullable=False),
    sa.Column('api_signature', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployed_integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('sequence_config', sa.JSON(), nullable=False),
    sa.Column('field_mappings', sa.JSON(), nullable=False),
    sa.Column('api_signature', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_field', sa.String(length=255), nullable=False),
    sa.Column('source_field_type', sa.Enum('STRING', 'NUMBER', 'BOOLEAN', 'OBJECT', 'ARRAY', 'DATE', 'EMAIL', 'PHONE', 'CURRENCY', name='datatype'), nullable=True),
    sa.Column('source_field_path', sa.String(length=500), nullable=True),
    sa.Column('target_field', sa.String(length=255), nullable=False),
    sa.Column('target_field_type', sa.Enum('STRING', 'NUMBER', 'BOOLEAN', 'OBJECT', 'ARRAY', 'DATE', 'EMAIL', 'PHONE', 'CURRENCY', name='datatype'), nullable=True),
    sa.Column('target_field_path', sa.String(length=500), nullable=True),
    sa.Column('transformation_type', sa.Enum('NONE', 'FORMAT_PHONE', 'FORMAT_DATE', 'FORMAT_CURRENCY', 'SPLIT_NAME', 'OBJECT_MAPPING', 'ARRAY_FORMAT', 'CONDITIONAL', 'CUSTOM', name='transformationtype'), nullable=True),
    sa.Column('transformation_config', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('fallback_value', sa.String(length=500), nullable=True),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_mappings_id'), 'field_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_field_mappings_name'), 'field_mappings', ['name'], unique=False)
    op.create_table('generated_apis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('generation_config', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('test_status', sa.String(length=50), nullable=True),
    sa.Column('is_deployed', sa.Boolean(), nullable=True),
    sa.Column('deployment_url', sa.String(length=500), nullable=True),
    sa.Column('last_deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation_time', sa.Integer(), nullable=True),
    sa.Column('complexity_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['api_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_apis_id'), 'generated_apis', ['id'], unique=False)
    op.create_index(op.f('ix_generated_apis_name'), 'generated_apis', ['name'], unique=False)
    op.create_table('integration_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence_type', sa.String(length=100), nullable=False),
    sa.Column('execution_mode', sa.String(length=50), nullable=True),
    sa.Column('condition_config', sa.JSON(), nullable=True),
    sa.Column('stop_on_error', sa.Boolean(), nullable=True),
    sa.Column('retry_failed_steps', sa.Boolean(), nullable=True),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_sequences_id'), 'integration_sequences', ['id'], unique=False)
    op.create_index(op.f('ix_integration_sequences_name'), 'integration_sequences', ['name'], unique=False)
    op.create_table('api_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_config_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('test_data', sa.JSON(), nullable=True),
    sa.Column('expected_response', sa.JSON(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_automated', sa.Boolean(), nullable=True),
    sa.Column('execution_order', sa.Integer(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_status', sa.String(length=50), nullable=True),
    sa.Column('last_run_duration', sa.Integer(), nullable=True),
    sa.Column('last_run_error', sa.Text(), nullable=True),
    sa.Column('avg_response_time', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Integer(), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=True),
    sa.Column('successful_runs', sa.Integer(), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_config_id'], ['api_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tests_id'), 'api_tests', ['id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('integration_type', sa.Enum('LEAD_SUBMISSION', 'STATUS_CHECK', 'BULK_UPLOAD', 'WEBHOOK', 'POLLING', 'SEQUENCE', name='integrationtype'), nullable=False),
    sa.Column('api_endpoint', sa.String(length=500), nullable=False),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('parent_sequence_id', sa.Integer(), nullable=True),
    sa.Column('is_sequence_step', sa.Boolean(), nullable=True),
    sa.Column('auth_type', sa.Enum('NONE', 'API_KEY', 'BEARER_TOKEN', 'BASIC_AUTH', 'OAUTH2', 'CUSTOM', name='authenticationtype'), nullable=False),
    sa.Column('auth_config', sa.JSON(), nullable=True),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_schema', sa.JSON(), nullable=True),
    sa.Column('response_schema', sa.JSON(), nullable=True),
    sa.Column('depends_on_fields', sa.JSON(), nullable=True),
    sa.Column('output_fields', sa.JSON(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=True),
    sa.Column('error_mapping', sa.JSON(), nullable=True),
    sa.Column('fallback_config', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'TESTING', 'ERROR', name='integrationstatus'), nullable=True),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.ForeignKeyConstraint(['parent_sequence_id'], ['integration_sequences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.create_index(op.f('ix_integrations_name'), 'integrations', ['name'], unique=False)
    op.create_table('integration_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('request_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('response_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['integration_sequences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_logs_id'), 'integration_logs', ['id'], unique=False)
    op.create_index(op.f('ix_integration_logs_lead_id'), 'integration_logs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_integration_logs_request_id'), 'integration_logs', ['request_id'], unique=False)
    op.create_table('integration_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('test_data', sa.JSON(), nullable=False),
    sa.Column('expected_response', sa.JSON(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=50), nullable=True),
    sa.Column('last_response', sa.JSON(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_tests_id'), 'integration_tests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_tests_id'), table_name='integration_tests')
    op.drop_table('integration_tests')
    op.drop_index(op.f('ix_integration_logs_request_id'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_lead_id'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_id'), table_name='integration_logs')
    op.drop_table('integration_logs')
    op.drop_index(op.f('ix_integrations_name'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_api_tests_id'), table_name='api_tests')
    op.drop_table('api_tests')
    op.drop_index(op.f('ix_integration_sequences_name'), table_name='integration_sequences')
    op.drop_index(op.f('ix_integration_sequences_id'), table_name='integration_sequences')
    op.drop_table('integration_sequences')
    op.drop_index(op.f('ix_generated_apis_name'), table_name='generated_apis')
    op.drop_index(op.f('ix_generated_apis_id'), table_name='generated_apis')
    op.drop_table('generated_apis')
    op.drop_index(op.f('ix_field_mappings_name'), table_name='field_mappings')
    op.drop_index(op.f('ix_field_mappings_id'), table_name='field_mappings')
    op.drop_table('field_mappings')
    op.drop_table('deployed_integrations')
    op.drop_table('deployed_apis')
    op.drop_index(op.f('ix_custom_target_fields_name'), table_name='custom_target_fields')
    op.drop_index(op.f('ix_custom_target_fields_id'), table_name='custom_target_fields')
    op.drop_table('custom_target_fields')
    op.drop_index(op.f('ix_api_configs_id'), table_name='api_configs')
    op.drop_table('api_configs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_master_source_fields_name'), table_name='master_source_fields')
    op.drop_index(op.f('ix_master_source_fields_id'), table_name='master_source_fields')
    op.drop_table('master_source_fields')
    op.drop_index(op.f('ix_lenders_name'), table_name='lenders')
    op.drop_index(op.f('ix_lenders_id'), table_name='lenders')
    op.drop_table('lenders')
    op.drop_index(op.f('ix_field_mapping_templates_name'), table_name='field_mapping_templates')
    op.drop_index(op.f('ix_field_mapping_templates_id'), table_name='field_mapping_templates')
    op.drop_table('field_mapping_templates')
    op.drop_index(op.f('ix_api_templates_name'), table_name='api_templates')
    op.drop_index(op.f('ix_api_templates_id'), table_name='api_templates')
    op.drop_table('api_templates')
    # ### end Alembic commands ###
